# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build"

on:
  pull_request:
    branches:
      - "v*.*"
  push:
    branches:
      - "v*.*"

jobs:
  tests:
    name: "Tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          extensions: mbstring

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-"

      - name: "Install dependencies"
        run: "composer update --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Security Checker"
        run: |
          wget -O local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/latest/download/local-php-security-checker_1.2.0_linux_amd64
          chmod +x local-php-security-checker
          ./local-php-security-checker

      - name: "Static Analysis"
        run: "vendor/bin/phpstan"

      - name: "Tests"
        run: "vendor/bin/behat"
